### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by artemgurzhii** [Artiikk/Word-Writer#1]
1. https://github.com/Artiikk/Word-Writer/blob/master/index.html#L9-L37
  - `data-item` - вроде не нужны
  - `onclick="toggleCheckbox(this)"` - так се, переделай на что-то получше)

2. https://github.com/Artiikk/Word-Writer/blob/master/index.js#L82
  - `wrapper` замени на `document.getElementById('wrapper');`, использовать хаки итд не оч хорошая идея)

3. ну и залей на `github-pages`

**Comment by Artiikk** [comment]
Done 👍
